CREATE DATABASE BUSINESS
USE BUSINESS
CREATE TABLE POSITION(
ID INT PRIMARY KEY IDENTITY,
POSITION NVARCHAR(50)
)
CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY IDENTITY,
POSITIONID INT REFERENCES POSITION(ID),
SAA NVARCHAR(50),
SALARY INT
)
CREATE TABLE BRANCHE(
ID INT PRIMARY KEY IDENTITY,
BRANCHE NVARCHAR(50),
)
CREATE TABLE PRODUCT(
ID INT PRIMARY KEY IDENTITY,
PRODUCT NVARCHAR(50),
PURCHASEPRICE INT,
SOLDPRICE INT
)
CREATE TABLE SALES(
ID INT PRIMARY KEY IDENTITY,
PRODUCTID INT REFERENCES PRODUCT(ID),
EMPLOYEEID INT REFERENCES EMPLOYEE(ID),
BRANCHEID INT REFERENCES BRANCHE(ID),
SOLDDATE DATE 
)

INSERT INTO POSITION VALUES ('TV SALER')
INSERT INTO POSITION VALUES ('PHONE SALER')
INSERT INTO POSITION VALUES ('DOOR SALER')
SELECT*FROM POSITION

INSERT INTO BRANCHE VALUES ('NARIMANOV')
INSERT INTO BRANCHE VALUES ('GANCLIK')
INSERT INTO BRANCHE VALUES ('SUMQAYIT')
SELECT*FROM BRANCHE

INSERT INTO PRODUCT VALUES ('LG TV',200,350)
INSERT INTO PRODUCT VALUES ('IPHONE',700,800)
INSERT INTO PRODUCT VALUES ('RED DOOR',100,150)
SELECT*FROM PRODUCT

INSERT INTO EMPLOYEE VALUES (1,'Emily',1000)
INSERT INTO EMPLOYEE VALUES (2,'Gulchin',1200)
INSERT INTO EMPLOYEE VALUES (3,'Simare',1150)
SELECT*FROM EMPLOYEE

INSERT INTO SALES VALUES (1,1,1,'2020/04/13')
INSERT INTO SALES VALUES (1,1,1,'2022/04/21')
INSERT INTO SALES VALUES (2,2,2,'2020/05/11')
INSERT INTO SALES VALUES (3,3,3,'2020/05/17')
INSERT INTO SALES VALUES (3,3,3,'2020/04/21')
SELECT*FROM SALES
--1
SELECT EMPLOYEE.SAA AS 'EMPLOYEES NAME',PRODUCT.PRODUCT AS 'PRODUCTS NAME',BRANCHE.BRANCHE AS 'BRANCHE NAME',PRODUCT.PURCHASEPRICE,PRODUCT.SOLDPRICE 
FROM SALES
LEFT JOIN 
EMPLOYEE ON EMPLOYEE.ID=SALES.ID
LEFT JOIN
PRODUCT ON PRODUCT.ID=SALES.ID
LEFT JOIN
BRANCHE ON BRANCHE.ID=SALES.ID

--2 BUTUN SATISLARIN CEMI
SELECT SUM(PRODUCT.SOLDPRICE) AS'SUM OF SALES PRICE' FROM SALES
LEFT JOIN 
PRODUCT ON PRODUCT.ID=SALES.PRODUCTID

--3 CARI AYDA MEHSUL SATISINDAN GELEN YEKUN MEBLEG (( NULL VERIR
SELECT SUM(PRODUCT.SOLDPRICE) AS'SUM OF CURRENT MONTH SALES PRICE' FROM SALES
LEFT JOIN
PRODUCT ON PRODUCT.ID=SALES.PRODUCTID
WHERE MONTH(SALES.SOLDDATE)=MONTH(GETDATE())

--4 HER ISCININ SATDIGI MEHSUL SAYINI TAP
SELECT COUNT(*) FROM SALES GROUP BY EMPLOYEEID	



--5Bugun erzinde en chox mehsul satan filial YAZAMMADM TAM
SELECT *
FROM SALES
INNER JOIN BRANCHE ON BRANCHE.ID=SALES.BRANCHEID
INNER JOIN PRODUCT ON PRODUCT.ID=SALES.PRODUCTID
WHERE SALES.SOLDDATE=GETDATE() GROUP BY MAX(COUNT(BRANCHE.ID))


